apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
    - image: nginx
      name: multi-pod
      env:
        - name: BACKEND_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-user
              key: backend-username
        - name: DN_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user
              key: db-username
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
