apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-test-pod
  name: secret-test-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
    - image: nginx
      name: test-container
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
