apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx:1.19
      name: nginx
      env:
        - name: MESSAGE
          value: "hello"
      resources: {}
      command: ["/bin/bash"]
      args: ["-c", "sleep 1000"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
